imports:
    - { resource: config.yml }
    - { resource: security_api.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_api.yml"

fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    body_listener:          true
    format_listener:        true
    view:
        serialize_null: false
        formats:
            json: true
    body_converter:
        enabled: true
        validate: true
    serializer:
        serialize_null: true

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: streamed
        streamed:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug