rest:
    type: rest
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc

faucon_dor:
    resource: "@FaucondorBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

api_rest_users :
  type: rest
  resource:     "@UserBundle/Controller/UserRestController.php"

api_rest_roles :
  type: rest
  resource:     "@FaucondorBundle/Controller/RoleRestController.php"