_api:
    resource: routing_api.yml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"

