reset:
    type: rest
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /api

faucon_dor:
    resource: "@FaucondorBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc