security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_DOC]
        ROLE_DOC:   [ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:            ^/
            context:            user
            anonymous:          true
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
                default_target_path: nelmio_api_doc_index
            logout:
                path:           fos_user_security_logout
                target:         nelmio_api_doc_index
                invalidate_session: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_DOC }