<?php

namespace UserBundle\Entity;

use FaucondorBundle\Entity\Post;
use FaucondorBundle\Entity\Section;
use Datetime;
use Symfony\Component\Validator\Constraints\Date;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchLoginActivity(){
        $qb = $this->createQueryBuilder('u');

        $date = date('Y-m-d');
        $date.= " 00:00:00";

        $qb
            ->select('COUNT(u)')
            ->where('u.lastLogin >= :date')
            ->setParameter('date', $date)
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findUsersByPost(Post $post){
        return $this->createQueryBuilder('u')
            ->innerJoin('u.posts', 'p', 'WITH', 'p.id = :post')
            ->setParameter('post', $post->getId())
            ->orderBy('u.firstname, u.lastname', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findUsersBySection(Section $section){
        return $this->createQueryBuilder('u')
            ->where('u.section = :section')
            ->setParameter('section', $section->getId())
            ->orderBy('u.firstname, u.lastname', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
