api_rest_users :
  type: rest
  resource:     "@RestBundle/Controller/UserRestController.php"

api_rest_roles :
  type: rest
  resource:     "@RestBundle/Controller/RoleRestController.php"

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"