index:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

faucondor_login_check:
    path:     /login_check
    defaults: { _controller: UserBundle:Login:check }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"