<?php

namespace FaucondorBundle\Entity;

/**
 * CommitteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitteeRepository extends \Doctrine\ORM\EntityRepository
{
}
