<?php

namespace FaucondorBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(){
        return $this->createQueryBuilder('p')
            ->orderBy('p.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findByLevel($level){
        return $this->createQueryBuilder('p')
            ->where('p.level = :level')->setParameter('level', $level)
            ->andWhere('p.role NOT IN (:roles)')->setParameter('roles', 'activeMember,regularBoardMember,projectCoordinator')
            ->orderBy('p.name', 'ASC');
    }
}
