<?php

namespace FaucondorBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(){
        return $this->createQueryBuilder('p')
            ->orderBy('p.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findByLevel($level){

        $levels = array();
        array_push($levels, $level);

        if (strtolower($level) == strtolower(Post::NATIONAL)) {
            array_push($levels, Post::LOCAL);
        }

        $builder = $this->createQueryBuilder('p')
            ->where('p.level in (:level)')->setParameter('level', $levels)
            ->andWhere('p.role NOT IN (:roles)')->setParameter('roles', 'activeMember,regularBoardMember,projectCoordinator')
            ->orderBy('p.name', 'ASC');

        return $builder;
    }

    public function findPostsByLevel($level){

        $builder = $this->createQueryBuilder('p')
            ->where('p.level = :level')->setParameter('level', $level)
            ->andWhere("p.role != 'regularBoardMember'")
            ->andWhere("p.role != 'projectCoordinator'")
            ->orderBy('p.name', 'ASC')
            ->getQuery()
            ->getResult();

        return $builder;
    }
}
