<?php

namespace FaucondorBundle\Entity;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSectionsByCountry($code_country){
        return $this->createQueryBuilder('s')
            ->where('s.country = :country')
            ->setParameter('country', $code_country)
            ->orderBy('s.name', 'ASC');
    }
}
